name: Weekly Wiki Sync

on:
  schedule:
    - cron: '0 0 * * 6' 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: pip install requests google-api-python-client google-auth
      - name: Run Python Script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          ZENROWS_API_KEY: ${{ secrets.ZENROWS_API_KEY }}
        run: python main.py